# Generated by Django 4.2 on 2025-01-06 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_publish',
            field=models.BooleanField(default=True),
        ),
    ]
