# Generated by Django 4.2.17 on 2025-01-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_is_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('_', '類型(全部)'), ('Elderly', '長者'), ('Youth', '青年'), ('Family', '家庭及兒童'), ('Class', '興趣班'), ('Communities', '社區共融'), ('Local', '本會資訊')], max_length=50),
        ),
    ]
