# Generated by Django 4.2.17 on 2025-01-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_delete_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('_', '類型(全部)'), ('Elderly', '長者'), ('Youth', '青年'), ('Family', '家庭及兒童'), ('Class', '興趣班'), ('Communities', '社區共融'), ('others', '其他')], max_length=50),
        ),
    ]
